### ISSUE TITLE
Превод в Разрешения

### ISSUE THREAD

**Issue by vlado05** [tmladenov/MIUI-V8-BULGARIAN#1]
Когато искам да забраня достъп до Смс-и примерно на някое приложение, в диалоговият прозорец вместо Отказ и Ок показва Отказ и Отказ. Дясният Отказ все пак действа като ОК, но просто е малко дразнещо. Благодаря ви. Лек ден

**Comment by tmladenov** [comment]
Здравей! Надявам се да съм го коригирал с https://github.com/tmladenov/MIUI-V8-BULGARIAN/commit/416707c7f1e1da843ab95e7d3978e00af6af5f7f. 
Очаквам да потвърдиш след петъчния ъпдейт, засега оставям проблема отворен.

**Comment by vlado05** [comment]
За съжаление не. 6.9.29

На вт, 27.09.2016 г., 20:02 Todor Mladenov notifications@github.com
написа:

**Comment by tmladenov** [comment]
Ще помоля за малко съдействие. Трябва ми снимка от екрана на това място, но телефона да бъде на английски език. Или поне какво точно пише на английски на десния бутон.

**Comment by Hristo-** [comment]
6.10.27

Например при опит да се изключи достъпа до контакти:

![untitled2](https://cloud.githubusercontent.com/assets/6107569/20033944/6f66232e-a3b6-11e6-850c-028e6396eb1f.png)
![untitled](https://cloud.githubusercontent.com/assets/6107569/20033945/6f6b61fe-a3b6-11e6-8a3f-94af19638a26.png)

**Comment by tmladenov** [comment]
Благодаря за съдействието. Така е по ясно. Би трябвало в следващата версия да е Забрани вече десния бутон. 
Очаквам да потвърдите, за да затворя темата.

**Comment by Hristo-** [comment]
Оправено е.

**Comment by vlado05** [comment]
OK мерси

На чт, 1.12.2016 г., 21:21 Hristo Hristov <notifications@github.com> написа:

**Comment by vlado05** [comment]
Здравей,абе да питам вие ли правите превода в официалния Глобал Ром

На сб, 7.01.2017 г., 0:11 Todor Mladenov <notifications@github.com> написа:
